### ISSUE TITLE
Feature/Add to Playlist

### ISSUE THREAD

**Issue by felicitybrammer** [ScalexanderB/activity-music#13]
Add either:
-drag and drop functionality
-an 'add track' button on each song listing ( + icon?)

**Comment by JunyaQ** [comment]
finish the add click button to local storage, let me know what info do you need for each song so I can put them in the local storage for your further development.
Currently only put the id, which is the URL for each song because that is the most unique and identical one 
Suggest: 
Can we make another page for the drop function, since this page is functionally complete, 
The local storage needs a name anyway, so we can use that to make drag function for separate to different folders to make the website looks more complete: 
drag function: localStorage(folderName,songuri)
